name: Bug report
description: Report a problem in an existing skill workflow
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What failed?
    validations:
      required: true
  - type: input
    id: skill
    attributes:
      label: Skill path
      placeholder: skills/conviso-vuln-remediator
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Include exact command sequence
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: checkboxes
    id: safety
    attributes:
      label: Safety checks
      options:
        - label: I removed any sensitive data from logs/output.
          required: true
