name: Feature request
description: Propose a new skill or workflow improvement
labels: [enhancement]
body:
  - type: dropdown
    id: type
    attributes:
      label: Request type
      options:
        - New skill
        - Improvement to existing skill
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What operational gap are you solving?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Include expected workflow and guardrails
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: How we know this is done
    validations:
      required: true
